### ISSUE TITLE
data_file KeyError

### ISSUE THREAD

**Issue by fonnesbeck** [pyro-ppl/pyro-models#11]
Attempting to run any of the models using the approach in the test script results in a `KeyError`. For example,

```python
models = pyro_models.load()
model_dict = models['arm.radon_intercept']
model = model_dict['model']
data = pyro_models.data(model_dict)
```
Results in:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Untitled-1 in 
      5 model_dict = models['arm.radon_intercept']
      6 model = model_dict['model']
----> 7 data = pyro_models.data(model_dict)
      8 # guide = AutoDelta(model)

~/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/Pyro_Models-0.0.0-py3.7.egg/pyro_models/utils.py in data(model)
     49 
     50 def data(model):
---> 51     data = json_file_to_mem_format(model['data_file'])
     52     foo = model['module']
     53 

KeyError: 'data_file'
```

Looking at the `model_dict`, there is indeed no `'data_file'` key:

```python

model_dict
{'dataset': 'arm',
 'source_file': '/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/Pyro_Models-0.0.0-py3.7.egg/pyro_models/arm/radon_intercept.py',
 'name': 'radon_intercept',
 'module': <module 'model.radon_intercept' from '/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/Pyro_Models-0.0.0-py3.7.egg/pyro_models/arm/radon_intercept.py'>,
 'model': functools.partial(<function load.<locals>.model_wrapped at 0x7f7c1fcf8830>, <module 'model.radon_intercept' from '/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/Pyro_Models-0.0.0-py3.7.egg/pyro_models/arm/radon_intercept.py'>)}
```

**Comment by fonnesbeck** [comment]
Confirming that even when the test suite is run from the command line, the same error is triggered:

```
❯ python test_models.py 
Traceback (most recent call last):
  File "/Users/cfonnesbeck/GitHub/pyro-models/tests/test_models.py", line 57, in <module>
    main(args)
  File "/Users/cfonnesbeck/GitHub/pyro-models/tests/test_models.py", line 39, in main
    data = pyro_models.data(model_dict)
  File "/Users/cfonnesbeck/miniforge3/envs/pyro/lib/python3.9/site-packages/Pyro_Models-0.0.0-py3.9.egg/pyro_models/utils.py", line 51, in data
    data = json_file_to_mem_format(model['data_file'])
KeyError: 'data_file'
```
